### ISSUE TITLE
Kurse unvollständig auf qgis.ch

### ISSUE THREAD

**Issue by itsakifa** [qgis-ch/qgis-ch-website#10]
Hallo QGIS.ch-Team,

Ich sehe gerade, dass die meisten unserer zweitägigen Kurse, die korrekt in https://github.com/qgis-ch/qgis-ch-website/blob/main/_data/kurse-cours.csv aufgeführt sind, auf der Website nicht sichtbar sind:

05.06. & 12.06.2024	OPENGIS.ch: QGIS Kurs Fortgeschrittene in Zürich
22.05. & 29.05.2024	OPENGIS.ch: QGIS Kurs Einsteiger in Zürich

22.10. & 29.10.2024	OPENGIS.ch: QGIS Cours avancé à Lausanne
01.10. & 15.10.2024	OPENGIS.ch: QGIS Cours de base à Lausanne

13.11. & 20.11.2024	        OPENGIS.ch: QGIS Kurs Fortgeschrittene in Bern

Haben wir was falsch erfasst? 

Danke fürs Korrigieren!

**Comment by webrian** [comment]
Bei zweitägigen Kursen muss die Jahreszahl bei beiden Daten vorkommen. Der Kurs wird gemäss dem ersten Datum eingeordnet.
